name: Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload to itch.io via Butler
        uses: manleybrands/action-itch-butler@v1.0.3
        with:
          butler_key: ${{ secrets.ITCH_IO_API_KEY }}
          game: oloosahad/colour-flood
          channel: html5
          directory: .
