name: Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Butler Client
        run: |
          npm install -g butler-cli

      - name: Push to Itch
        run: |
          butler push . oloosahad/colour-flood:html5 --key ${{ secrets.ITCH_IO_API_KEY }}
